# builder_adhkar_hadith.py

# 40 Rabbana Duas
rabbana_duas = [
    ("رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ", "Rabbana taqabbal minna innaka Antas-Samee'ul-Aleem", "اے ہمارے رب! ہم سے (یہ خدمت) قبول فرما، بے شک تو ہی خوب سننے والا خوب جاننے والا ہے۔", "Our Lord, accept [this] from us. Indeed You are the Hearing, the Knowing.", "سورۃ البقرۃ 2:127", "Quranic Duas"),
    ("رَبَّنَا وَاجْعَلْنَا مُسْلِمَيْنِ لَكَ وَمِن ذُرِّيَّتِنَا أُمَّةً مُّسْلِمَةً لَّكَ", "Rabbana waj'alna muslimayni laka wa min dhurriyyatina ummatan muslimatan laka", "اے ہمارے رب! ہمیں اپنا فرمانبردار بنا اور ہماری اولاد میں سے بھی ایک ایسی جماعت پیدا کر جو تیری مطیع ہو۔", "Our Lord, and make us submissive to You and from our descendants a nation submissive to You.", "سورۃ البقرۃ 2:128", "Quranic Duas"),
    ("رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ", "Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina 'adhaban-nar", "اے ہمارے رب! ہمیں دنیا میں بھی بھلائی عطا فرما اور آخرت میں بھی بھلائی عطا فرما اور ہمیں آگ کے عذاب سے بچا۔", "Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.", "سورۃ البقرۃ 2:201", "Quranic Duas"),
    ("رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ", "Rabbana afrigh 'alayna sabran wa thabbit aqdamana wansurna 'alal-qawmil-kafirin", "اے ہمارے رب! ہم پر صبر کے دہانے کھول دے، ہمارے قدموں کو جما دے اور کافروں کے مقابلے میں ہماری مدد فرما۔", "Our Lord, pour upon us patience and plant firmly our feet and give us victory over the disbelieving people.", "سورۃ البقرۃ 2:250", "Quranic Duas"),
    ("رَبَّنَا لَا تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا", "Rabbana la tu'akhidhna in naseena aw akhta'na", "اے ہمارے رب! اگر ہم بھول جائیں یا ہم سے خطا ہو جائے تو ہماری پکڑ نہ فرما۔", "Our Lord, do not impose blame upon us if we have forgotten or erred.", "سورۃ البقرۃ 2:286", "Quranic Duas"),
    ("رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِن قَبْلِنَا", "Rabbana wa la tahmil 'alayna isran kama hamaltahu 'alal-ladhina min qablina", "اے ہمارے رب! ہم پر وہ بوجھ نہ ڈال جو تو نے ہم سے پہلے لوگوں پر ڈالا تھا۔", "Our Lord, and lay not upon us a burden like that which You laid upon those before us.", "سورۃ البقرۃ 2:286", "Quranic Duas"),
    ("رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ ۖ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا", "Rabbana wa la tuhammilna ma la taqata lana bih, wa'fu 'anna waghfir lana warhamna", "اے ہمارے رب! ہم سے وہ بوجھ نہ اٹھوا جس کی ہم میں طاقت نہیں، اور ہم سے درگزر فرما، ہمیں بخش دے اور ہم پر رحم فرما۔", "Our Lord, and burden us not with that which we have no ability to bear. And pardon us; and forgive us; and have mercy upon us.", "سورۃ البقرۃ 2:286", "Quranic Duas"),
    ("رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً", "Rabbana la tuzigh quloobana ba'da idh hadaytana wa hab lana mil-ladunka rahmah", "اے ہمارے رب! ہدایت دینے کے بعد ہمارے دلوں کو ٹیڑھا نہ فرما اور ہمیں اپنے پاس سے خاص رحمت عطا فرما۔", "Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy.", "سورۃ آل عمران 3:8", "Quranic Duas"),
    ("رَبَّنَا إِنَّكَ جَامِعُ النَّاسِ لِيَوْمٍ لَّا رَيْبَ فِيهِ", "Rabbana innaka jami'un-nasi li-yawmil-la rayba feeh", "اے ہمارے پروردگار! بے شک تو تمام انسانوں کو اس دن جمع کرنے والا ہے جس کے آنے میں کوئی شک نہیں۔", "Our Lord, surely You will gather the people for a Day about which there is no doubt.", "سورۃ آل عمران 3:9", "Quranic Duas"),
    ("رَبَّنَا إِنَّنَا آمَنَّا فَاغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ النَّارِ", "Rabbana innana amanna faghfir lana dhunoobana wa qina 'adhaban-nar", "اے ہمارے رب! ہم ایمان لائے، پس ہمارے گناہ بخش دے اور ہمیں آگ کے عذاب سے بچا۔", "Our Lord, indeed we have believed, so forgive us our sins and protect us from the punishment of the Fire.", "سورۃ آل عمران 3:16", "Quranic Duas"),
    ("رَبَّنَا آمَنَّا بِمَا أَنزَلْتَ وَاتَّبَعْنَا الرَّسُولَ فَاكْتُبْنَا مَعَ الشَّاهِدِينَ", "Rabbana amanna bima anzalta wattaba'nar-rasoola faktubna ma'ash-shahideen", "اے ہمارے رب! جو تو نے نازل فرمایا ہم اس پر ایمان لائے اور ہم نے رسول کی پیروی کی، پس ہمیں گواہی دینے والوں میں لکھ لے۔", "Our Lord, we have believed in what You revealed and have followed the messenger, so register us among the witnesses.", "سورۃ آل عمران 3:53", "Quranic Duas"),
    ("رَبَّنَا اغْفِرْ لَنَا ذُنُوبَنَا وَإِسْرَافَنَا فِي أَمْرِنَا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ", "Rabbana-ghfir lana dhunoobana wa israfana fee amrina wa thabbit aqdamana wansurna", "اے ہمارے رب! ہمارے گناہوں اور ہماری زیادتیوں کو بخش دے، ہمارے قدم جمائے رکھ اور کافروں پر ہماری مدد فرما۔", "Our Lord, forgive us our sins and the excess in our affairs and plant firmly our feet and give us victory.", "سورۃ آل عمران 3:147", "Quranic Duas"),
    ("رَبَّنَا مَا خَلَقْتَ هَٰذَا بَاطِلًا سُبْحَانَكَ فَقِنَا عَذَابَ النَّارِ", "Rabbana ma khalaqta hadha batila, subhanaka faqina 'adhaban-nar", "اے ہمارے رب! تو نے یہ سب بے مقصد پیدا نہیں کیا، تو پاک ہے، پس ہمیں دوزخ کے عذاب سے بچا۔", "Our Lord, You did not create this aimlessly; exalted are You; then protect us from the punishment of the Fire.", "سورۃ آل عمران 3:191", "Quranic Duas"),
    ("رَبَّنَا إِنَّكَ مَن تُدْخِلِ النَّارَ فَقَدْ أَخْزَيْتَهُ ۖ وَمَا لِلظَّالِمِينَ مِنْ أَنصَارٍ", "Rabbana innaka man tudkhilin-nara faqad akhzaytah", "اے ہمارے رب! جسے تو نے آگ میں ڈال دیا اسے تو نے یقیناً رسوا کر دیا، اور ظالموں کا کوئی مددگار نہیں۔", "Our Lord, indeed whoever You admit to the Fire - You have disgraced him, and for the wrongdoers there are no helpers.", "سورۃ آل عمران 3:192", "Quranic Duas"),
    ("رَّبَّنَا إِنَّنَا سَمِعْنَا مُنَادِيًا يُنَادِي لِلْإِيمَانِ أَنْ آمِنُوا بِرَبِّكُمْ فَآمَنَّا", "Rabbana innana sami'na munadiyan yunadi lil-imani an aminoo bi-Rabbikum fa-amanna", "اے ہمارے رب! ہم نے ایک پکارنے والے کو سنا جو ایمان کی طرف پکار رہا تھا کہ اپنے رب پر ایمان لاؤ، تو ہم ایمان لے آئے۔", "Our Lord, indeed we have heard a caller calling to faith, [saying], 'Believe in your Lord,' and we have believed.", "سورۃ آل عمران 3:193", "Quranic Duas"),
    ("رَبَّنَا فَاغْفِرْ لَنَا ذُنُوبَنَا وَكَفِّرْ عَنَّا سَيِّئَاتِنَا وَتَوَفَّنَا مَعَ الْأَبْرَارِ", "Rabbana faghfir lana dhunoobana wa kaffir 'anna sayyi'atina wa tawaffana ma'al-abrar", "اے ہمارے رب! پس ہمارے گناہ بخش دے، ہماری برائیوں کو مٹا دے اور ہمیں نیک لوگوں کے ساتھ وفات عطا فرما۔", "Our Lord, so forgive us our sins and remove from us our misdeeds and cause us to die with the righteous.", "سورۃ آل عمران 3:193", "Quranic Duas"),
    ("رَبَّنَا وَآتِنَا مَا وَعَدتَّنَا عَلَىٰ رُسُلِكَ وَلَا تُخْزِنَا يَوْمَ الْقِيَامَةِ", "Rabbana wa atina ma wa'adtana 'ala rusulika wa la tukhzina yawmal-qiyamah", "اے ہمارے رب! اور ہمیں وہ سب عطا فرما جس کا تو نے اپنے رسولوں کے ذریعے ہم سے وعدہ فرمایا ہے اور ہمیں قیامت کے دن رسوا نہ فرما۔", "Our Lord, and grant us what You promised us through Your messengers and do not disgrace us on the Day of Resurrection.", "سورۃ آل عمران 3:194", "Quranic Duas"),
    ("رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ", "Rabbana dhalamna anfusana wa il-lam taghfir lana wa tarhamna lana-koonanna minal-khasireen", "اے ہمارے رب! ہم نے اپنی جانوں پر ظلم کیا، اور اگر تو نے ہمیں معاف نہ فرمایا اور ہم پر رحم نہ کیا تو ہم نقصان پانے والوں میں ہوں گے۔", "Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.", "سورۃ الاعراف 7:23", "Quranic Duas"),
    ("رَبَّنَا لَا تَجْعَلْنَا مَعَ الْقَوْمِ الظَّالِمِينَ", "Rabbana la taj'alna ma'al-qawmiz-zalimeen", "اے ہمارے رب! ہمیں ظالم لوگوں کے ساتھ شامل نہ فرما۔", "Our Lord, do not place us with the wrongdoing people.", "سورۃ الاعراف 7:47", "Quranic Duas"),
    ("رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَتَوَفَّنَا مُسْلِمِينَ", "Rabbana afrigh 'alayna sabran wa tawaffana muslimeen", "اے ہمارے رب! ہم پر صبر انڈیل دے اور ہمیں اسلام کی حالت میں موت عطا فرما۔", "Our Lord, pour upon us patience and let us die as Muslims [in submission to You].", "سورۃ الاعراف 7:126", "Quranic Duas"),
    ("رَبَّنَا لَا تَجْعَلْنَا فِتْنَةً لِّلْقَوْمِ الظَّالِمِينَ وَنَجِّنَا بِرَحْمَتِكَ مِنَ الْقَوْمِ الْكَافِرِينَ", "Rabbana la taj'alna fitnatal-lil-qawmiz-zalimeen, wa najjina bi-rahmatika", "اے ہمارے پروردگار! ہمیں ظالموں کے لیے آزمائش نہ بنا اور اپنی رحمت سے ہمیں کافر قوم سے نجات عطا فرما۔", "Our Lord, make us not [objects of] trial for the wrongdoing people and save us by Your mercy from the disbelieving people.", "سورۃ یونس 10:85-86", "Quranic Duas"),
    ("رَبَّنَا إِنَّكَ تَعْلَمُ مَا نُخْفِي وَمَا نُعْلِنُ", "Rabbana innaka ta'lamu ma nukhfee wa ma nu'lin", "اے ہمارے رب! بے شک تو جانتا ہے جو ہم چھپاتے ہیں اور جو ہم ظاہر کرتے ہیں۔", "Our Lord, indeed You know what we conceal and what we declare.", "سورۃ ابراہیم 14:38", "Quranic Duas"),
    ("رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِن ذُرِّيَّتِي ۚ رَبَّنَا وَتَقَبَّلْ دُعَاءِ", "Rabbij-'alnee muqeemas-salati wa min dhurriyyatee, Rabbana wa taqabbal du'a", "اے میرے پروردگار! مجھے نماز قائم کرنے والا بنا اور میری اولاد میں سے بھی، اے ہمارے رب! میری دعا قبول فرما۔", "My Lord, make me an establisher of prayer, and [many] from my descendants. Our Lord, and accept my supplication.", "سورۃ ابراہیم 14:40", "Quranic Duas"),
    ("رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ", "Rabbana-ghfir lee wa li-walidayya wa lil-mu'mineena yawma yaqoomul-hisab", "اے ہمارے رب! مجھے، میرے والدین کو اور تمام مومنوں کو اس دن بخش دے جس دن حساب قائم ہوگا۔", "Our Lord, forgive me and my parents and the believers the Day the account is established.", "سورۃ ابراہیم 14:41", "Quranic Duas"),
    ("رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا", "Rabbir-hamhuma kama rabbayanee sagheera", "اے میرے رب! ان دونوں (والدین) پر رحم فرما جیسا کہ انہوں نے بچپن میں مجھے پالا۔", "My Lord, have mercy upon them as they brought me up [when I was] small.", "سورۃ الاسراء 17:24", "Quranic Duas"),
    ("رَّبِّ أَدْخِلْنِي مُدْخَلَ صِدْقٍ وَأَخْرِجْنِي مُخْرَجَ صِدْقٍ وَاجْعَل لِّي مِن لَّدُنكَ سُلْطَانًا نَّصِيرًا", "Rabbi adkhilnee mudkhala sidqin wa akhrijnee mukhraja sidq", "اے میرے رب! مجھے سچائی کے ساتھ داخل فرما اور سچائی کے ساتھ نکال اور مجھے اپنے پاس سے مددگار غلبہ عطا فرما۔", "My Lord, cause me to enter a sound entrance and to exit a sound exit and grant me from Yourself a supporting authority.", "سورۃ الاسراء 17:80", "Quranic Duas"),
    ("رَبَّنَا آتِنَا مِن لَّدُنكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا", "Rabbana atina mil-ladunka rahmatan wa hayyi' lana min amrina rashada", "اے ہمارے رب! ہمیں اپنے پاس سے خاص رحمت عطا فرما اور ہمارے معاملے میں ہمارے لیے بھلائی اور درست رہنمائی مہیا فرما۔", "Our Lord, grant us from Yourself mercy and prepare for us from our affair right guidance.", "سورۃ الکہف 18:10", "Quranic Duas"),
    ("رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِّن لِّسَانِي يَفْقَهُوا قَوْلِي", "Rabbish-rah lee sadree wa yassir lee amree wahlul 'uqdatan mil-lisanee yafqahoo qawlee", "اے میرے رب! میرا سینہ کھول دے، میرا کام آسان فرما اور میری زبان کی گرہ سلجھا دے تاکہ لوگ میری بات سمجھ سکیں۔", "My Lord, expand for me my breast and ease for me my task and untie the knot from my tongue that they may understand my speech.", "سورۃ طٰہٰ 20:25-28", "Quranic Duas"),
    ("رَّبِّ زِدْنِي عِلْمًا", "Rabbi zidnee 'ilma", "اے میرے رب! میرے علم میں اضافہ فرما۔", "My Lord, increase me in knowledge.", "سورۃ طٰہٰ 20:114", "Quranic Duas"),
    ("أَنِّي مَسَّنِيَ الضُّرُّ وَأَنتَ أَرْحَمُ الرَّاحِمِينَ", "Annee massaniyad-durru wa Anta Arhamur-Rahimeen", "مجھے تکلیف پہنچی ہے اور تو سب رحم کرنے والوں سے بڑھ کر رحم فرمانے والا ہے۔", "Indeed, adversity has touched me, and you are the Most Merciful of the merciful.", "سورۃ الانبیاء 21:83", "Quranic Duas"),
    ("لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ", "La ilaha illa Anta subhanaka innee kuntu minaz-zalimeen", "تیرے سوا کوئی معبود نہیں، تو پاک ہے، بے شک میں ہی قصورواروں میں سے تھا۔", "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.", "سورۃ الانبیاء 21:87", "Quranic Duas"),
    ("رَبِّ لَا تَذَرْنِي فَرْدًا وَأَنتَ خَيْرُ الْوَارِثِينَ", "Rabbi la tadharnee fardan wa Anta khayrul-waritheen", "اے میرے رب! مجھے اکیلا نہ چھوڑ اور تو سب سے بہتر وارث ہے۔", "My Lord, do not leave me alone [with no heir], while you are the best of inheritors.", "سورۃ الانبیاء 21:89", "Quranic Duas"),
    ("رَّبِّ اغْفِرْ وَارْحَمْ وَأَنتَ خَيْرُ الرَّاحِمِينَ", "Rabbigh-fir warham wa Anta khayrur-rahimeen", "اے میرے رب! بخش دے اور رحم فرما اور تو سب سے بہترین رحم فرمانے والا ہے۔", "My Lord, forgive and have mercy, and You are the best of the merciful.", "سورۃ المؤمنون 23:118", "Quranic Duas"),
    ("رَبَّنَا اصْرِفْ عَنَّا عَذَابَ جَهَنَّمَ ۖ إِنَّ عَذَابَهَا كَانَ غَرَامًا", "Rabbanas-rif 'anna 'adhaba jahannama inna 'adhabaha kana gharama", "اے ہمارے رب! ہم سے جہنم کا عذاب پھیر دے، بے شک اس کا عذاب چمٹ جانے والا ہے۔", "Our Lord, avert from us the punishment of Hell. Indeed, its punishment is ever adhering.", "سورۃ الفرقان 25:65", "Quranic Duas"),
    ("رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا", "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqeena imama", "اے ہمارے رب! ہمیں ہماری بیویوں اور ہماری اولاد کی طرف سے آنکھوں کی ٹھنڈک عطا فرما اور ہمیں پرہیزگاروں کا پیشوا بنا۔", "Our Lord, grant us from among our wives and offspring comfort to our eyes and make us a leader for the righteous.", "سورۃ الفرقان 25:74", "Quranic Duas"),
    ("رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَىٰ وَالِدَيَّ", "Rabbi awzi'nee an ashkura ni'matakal-latee an'amta 'alayya wa 'ala walidayya", "اے میرے رب! مجھے توفیق دے کہ میں تیری اس نعمت کا شکر ادا کروں جو تو نے مجھ پر اور میرے والدین پر فرمائی۔", "My Lord, enable me to be grateful for Your favor which You have bestowed upon me and upon my parents.", "سورۃ النمل 27:19", "Quranic Duas"),
    ("رَبِّ إِنِّي ظَلَمْتُ نَفْسِي فَاغْفِرْ لِي", "Rabbi innee dhalamtu nafsee faghfir lee", "اے میرے پروردگار! میں نے اپنی جان پر زیادتی کی پس مجھے بخش دے۔", "My Lord, indeed I have wronged myself, so forgive me.", "سورۃ القصص 28:16", "Quranic Duas"),
    ("رَبِّ إِنِّي لِمَا أَنزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ", "Rabbi innee lima anzalta ilayya min khayrin faqeer", "اے میرے رب! تو جو بھلائی بھی میری طرف نازل فرما دے میں اس کا محتاج ہوں۔", "My Lord, indeed I am, for whatever good You would send down to me, in need.", "سورۃ القصص 28:24", "Quranic Duas"),
    ("رَبَّنَا وَسِعْتَ كُلَّ شَيْءٍ رَّحْمَةً وَعِلْمًا فَاغْفِرْ لِلَّذِينَ تَابُوا وَاتَّبَعُوا سَبِيلَكَ", "Rabbana wasi'ta kulla shay'in rahmatan wa 'ilman faghfir lilladhina taboo", "اے ہمارے رب! تیری رحمت اور علم ہر چیز پر محیط ہے پس ان لوگوں کو بخش دے جنہوں نے توبہ کی اور تیری راہ چلی۔", "Our Lord, You have encompassed all things in mercy and knowledge, so forgive those who have repented and followed Your way.", "سورۃ غافر 40:7", "Quranic Duas"),
    ("رَبَّنَا اغْفِرْ لَنَا وَلِإِخْوَانِنَا الَّذِينَ سَبَقُونَا بِالْإِيمَانِ وَلَا تَجْعَلْ فِي قُلُوبِنَا غِلًّا لِّلَّذِينَ آمَنُوا", "Rabbana-ghfir lana wa li-ikhwaninal-ladhina sabaqoona bil-eeman", "اے ہمارے رب! ہمیں اور ہمارے ان بھائیوں کو بخش دے جو ہم سے پہلے ایمان لائے اور ہمارے دلوں میں اہل ایمان کے لیے کینہ نہ رکھ۔", "Our Lord, forgive us and our brothers who preceded us in faith and put not in our hearts any resentment toward those who have believed.", "سورۃ الحشر 59:10", "Quranic Duas")
]

for idx, (ar, tr, ur, en, src, cat) in enumerate(rabbana_duas, 1):
    all_items.append({
        "id": f"rabbana_{idx}",
        "arabic": ar,
        "transliteration": tr,
        "translationUrdu": ur,
        "translation": en,
        "contemplativeNote": "قرآن مجید کی جامع ترین دعاؤں میں سے ایک، خلوص دل سے مانگیں۔",
        "category": "Quranic Duas (قرآنی دعائیں)",
        "source": src,
        "virtue": "قرآنی دعا کی برکت سے اللہ تعالیٰ دنیا اور آخرت سنوار دیتا ہے۔",
        "defaultDurationSeconds": 15
    })

# Authentic Adhkar, Hadiths, Daily Remembrances to reach over 1000 items
categories_list = [
    ("Morning & Evening (صبح و شام)", "صبح و شام کے مسنون اذکار جو ہر بلا اور مصیبت سے محفوظ رکھتے ہیں"),
    ("After Salah (نماز کے بعد)", "فرض نماز کے بعد کے مسنون اذکار جن سے گناہ معاف اور درجات بلند ہوتے ہیں"),
    ("Forgiveness (توبہ و استغفار)", "استغفار دل کے زنگ کو دور کرتا ہے اور رزق کے دروازے کھولتا ہے"),
    ("Gratitude (حمد و شکر)", "اللہ کا شکر ادا کرنے سے نعمتوں میں بے پناہ اضافہ ہوتا ہے"),
    ("Protection (حفاظت و پناہ)", "شیاطین، نظر بد اور اچانک حادثات سے پناہ کی دعائیں"),
    ("Hadith Nabawi (احادیث مبارکہ)", "رسول اللہ ﷺ کے سنہری ارشادات جو زندگی کو روشن کرتے ہیں")
]

adhkar_hadith_database = [
    # Adhkar Morning/Evening
    ("سُبْحَانَ اللَّٰهِ الْعَظِيمِ وَبِحَمْدِهِ", "Subhan-Allahil-Azeemi wa bihamdihi", "عظمت والا اللہ پاک ہے اور اپنی تعریفوں کے ساتھ۔", "Glory be to Allah the Magnificent, and praise is His.", "صحیح مسلم 2691", "Morning & Evening (صبح و شام)", "جنت میں کھجور کا ایک سایہ دار درخت لگا دیا جاتا ہے۔"),
    ("لَا إِلَٰهَ إِلَّا اللَّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", "La ilaha illallahu wahdahu la shareeka lah, lahul-mulku wa lahul-hamdu wa Huwa 'ala kulli shay'in qadeer", "اللہ کے سوا کوئی معبود نہیں، وہ اکیلا ہے اس کا کوئی شریک نہیں، اسی کی بادشاہی ہے اور اسی کے لیے تمام حمد ہے اور وہ ہر چیز پر قادر ہے۔", "None has the right to be worshiped but Allah alone, having no partner.", "صحیح بخاری 6403", "Morning & Evening (صبح و شام)", "دس غلام آزاد کرنے کا ثواب، 100 نیکیاں لکھی جاتی ہیں اور 100 گناہ معاف ہوتے ہیں۔"),
    ("يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ وَلَا تَكِلْنِي إِلَىٰ نَفْسِي طَرْفَةَ عَيْنٍ", "Ya Hayyu Ya Qayyoomu bi-rahmatika astagheeth, aslih lee sha'nee kullahu wa la takilnee ila nafsee tarfata 'ayn", "اے ہمیشہ زندہ رہنے والے، اے سب کو سنبھالنے والے! میں تیری ہی رحمت کی فریاد کرتا ہوں، میرا ہر کام سنوار دے اور مجھے آنکھ جھپکنے کی دیر بھی میرے نفس کے حوالے نہ فرما۔", "O Ever-Living, O Sustainer, in Your mercy I seek relief. Rectify for me all my affairs and leave me not to myself even for the blink of an eye.", "سنن نسائی 10405", "Morning & Evening (صبح و شام)", "ہر صبح و شام پڑھنے سے تمام معاملات اللہ کی امان میں آ جاتے ہیں۔"),
    ("اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لَا إِلَٰهَ إِلَّا أَنْتَ", "Allahumma 'afinee fee badanee, Allahumma 'afinee fee sam'ee, Allahumma 'afinee fee basaree", "اے اللہ! میرے بدن میں عافیت عطا فرما، اے اللہ! میری سماعت میں عافیت عطا فرما، اے اللہ! میری بصارت میں عافیت عطا فرما، تیرے سوا کوئی معبود نہیں۔", "O Allah, grant me health in my body, grant me health in my hearing, grant me health in my sight.", "سنن ابوداؤد 5090", "Morning & Evening (صبح و شام)", "تین بار صبح اور تین بار شام پڑھنے سے اعضاء کی سلامتی نصیب ہوتی ہے۔"),
    ("اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ، وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ", "Allahumma innee a'oodhu bika minal-kufri wal-faqr, wa a'oodhu bika min 'adhabil-qabr", "اے اللہ! میں کفر اور محتاجی سے تیری پناہ مانگتا ہوں اور عذاب قبر سے تیری پناہ مانگتا ہوں۔", "O Allah, I seek refuge in You from disbelief and poverty, and from the punishment of the grave.", "سنن ابوداؤد 5090", "Morning & Evening (صبح و شام)", "قبر کی سختیوں اور معاشی تنگی سے نجات کا نبوی نسخہ۔"),
    ("حَسْبِيَ اللَّٰهُ لَا إِلَٰهَ إِلَّا هُوَ ۖ عَلَيْهِ تَوَكَّلْتُ ۖ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ", "Hasbiyallahu la ilaha illa Huwa, 'alayhi tawakkaltu wa Huwa Rabbul-'Arshil-'Azeem", "مجھے اللہ ہی کافی ہے اس کے سوا کوئی معبود نہیں، اسی پر میں نے بھروسہ کیا اور وہ عرش عظیم کا پروردگار ہے۔", "Sufficient for me is Allah; there is no deity except Him. On Him I have relied, and He is the Lord of the Great Throne.", "سنن ابوداؤد 5081", "Morning & Evening (صبح و شام)", "جو صبح و شام سات مرتبہ پڑھے، اللہ اس کی دنیا و آخرت کی تمام پریشانیوں کو کافی ہو جاتا ہے۔"),
    ("أَعُوذُ بِكَلِمَاتِ اللَّٰهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ", "A'oodhu bi-kalimatil-lahit-tammati min sharri ma khalaq", "میں اللہ کے مکمل کلمات کی پناہ مانگتا ہوں اس کی پیدا کردہ تمام چیزوں کے شر سے۔", "I seek refuge in the perfect words of Allah from the evil of what He has created.", "صحیح مسلم 2709", "Protection (حفاظت و پناہ)", "شام کو پڑھنے والے کو زہریلا جانور یا کوئی نقصان نہیں پہنچا سکتا۔"),
    ("اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ", "Allahumma innee as'alukal-'afwa wal-'afiyata fid-dunya wal-akhirah", "اے اللہ! میں تجھ سے دنیا اور آخرت میں معافی اور عافیت کا طلبگار ہوں۔", "O Allah, I ask You for pardon and well-being in this world and the next.", "سنن ابن ماجہ 3871", "Morning & Evening (صبح و شام)", "عافیت کی دعا سے بڑھ کر کوئی نعمت نہیں مانگی گئی۔"),
    ("اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا", "Allahumma innee as'aluka 'ilman nafi'an, wa rizqan tayyiban, wa 'amalan mutaqabbala", "اے اللہ! میں تجھ سے نفع بخش علم، پاکیزہ حلال رزق اور قبول ہونے والے عمل کا سوال کرتا ہوں۔", "O Allah, I ask You for beneficial knowledge, good livelihood, and accepted deed.", "سنن ابن ماجہ 925", "After Salah (نماز کے بعد)", "فجر کی نماز کے بعد پڑھنا مسنون ہے۔"),
    ("سُبْحَانَ الْمَلِكِ الْقُدُّوسِ", "Subhanal-Malikil-Quddoos", "پاک ہے وہ بادشاہ جو بے حد مقدس ہے۔", "Glory be to the Sovereign, the Most Holy.", "سنن نسائی 1732", "After Salah (نماز کے بعد)", "نماز وتر کے بعد تین مرتبہ بلند آواز سے کہنا مسنون ہے۔"),
    ("اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ", "Allahumma Antas-Salamu wa minkas-salam, tabarakta ya Dhal-Jalali wal-Ikram", "اے اللہ! تو ہی سراپا سلامتی ہے اور سلامتی تیری ہی طرف سے ہے، تو بڑی برکت والا ہے اے عظمت اور عزت والے!", "O Allah, You are Peace and from You comes peace. Blessed are You, O Owner of majesty and honor.", "صحیح مسلم 591", "After Salah (نماز کے بعد)", "ہر فرض نماز کے سلام کے فورا بعد کا مسنون ذکر۔"),
    ("اللَّهُمَّ أَعِنِّي عَلَىٰ ذِكْرِكَ، وَشُكْرِكَ، وَحُسْنِ عِبَادَتِكَ", "Allahumma a'innee 'ala dhikrika, wa shukrika, wa husni 'ibadatika", "اے اللہ! اپنے ذکر، اپنے شکر اور اپنی بہترین عبادت پر میری مدد فرما۔", "O Allah, help me remember You, express gratitude to You, and worship You in the best manner.", "سنن ابوداؤد 1522", "After Salah (نماز کے بعد)", "رسول اللہ ﷺ نے حضرت معاذ بن جبل رضی اللہ عنہ کو ہر نماز کے بعد پڑھنے کی وصیت فرمائی۔"),
    ("أَسْتَغْفِرُ اللَّٰهَ الْعَظِيمَ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ", "Astaghfirullahal-'Azeemalladhi la ilaha illa Huwal-Hayyul-Qayyoomu wa atoobu ilayh", "میں اس عظمت والے اللہ سے بخشش مانگتا ہوں جس کے سوا کوئی معبود نہیں، وہ ہمیشہ زندہ اور سب کو قائم رکھنے والا ہے اور میں اسی کی طرف توبہ کرتا ہوں۔", "I seek forgiveness of Allah the Magnificent, none has the right to be worshiped but Him.", "سنن ترمذی 3577", "Forgiveness (توبہ و استغفار)", "جو یہ کہے اس کے گناہ معاف کر دیے جاتے ہیں چاہے میدان جنگ سے بھاگا ہو۔"),
    ("اللَّهُمَّ اغْفِرْ لِي خَطِيئَتِي وَجَهْلِي، وَإِسْرَافِي فِي أَمْرِي، وَمَا أَنْتَ أَعْلَمُ بِهِ مِنِّي", "Allahummagh-fir lee khatee'atee wa jahlee, wa israfee fee amree", "اے اللہ! میری غلطیاں، میری نادانی، میرے کاموں میں میری زیادتیاں اور وہ سب خطائیں بخش دے جنہیں تو مجھ سے زیادہ جانتا ہے۔", "O Allah, forgive my errors, my ignorance, my excess in my affairs, and what You know better than I.", "صحیح بخاری 6398", "Forgiveness (توبہ و استغفار)", "رسول اللہ ﷺ کی عاجزانہ مغفرت کی دعا۔"),
    ("اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي", "Allahumma innaka 'Afuwwun tuhibbul-'afwa fa'fu 'annee", "اے اللہ! بے شک تو بہت معاف فرمانے والا ہے، معافی کو پسند فرماتا ہے، پس مجھے معاف فرما دے۔", "O Allah, You are Forgiving and love forgiveness, so forgive me.", "جامع ترمذی 3513", "Forgiveness (توبہ و استغفار)", "شب قدر کی سب سے افضل اور محبوب ترین دعا۔"),
    ("الْحَمْدُ لِلَّٰهِ حَمْدًا كَثِيرًا طَيِّبًا مُبَارَكًا فِيهِ", "Alhamdulillahi hamdan katheeran tayyiban mubarakan feeh", "تمام تعریفیں اللہ کے لیے ہیں، بہت زیادہ تعریف، پاکیزہ اور برکتوں والی تعریف۔", "Praise be to Allah, abundant, pure, full of blessings.", "صحیح بخاری 799", "Gratitude (حمد و شکر)", "تیس سے زائد فرشتے اس کے ثواب کو پہلے لکھنے کے لیے لپکے۔"),
    ("الْحَمْدُ لِلَّٰهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ", "Alhamdulillahil-ladhee bi-ni'matihi tatimmus-salihat", "سب تعریفیں اس اللہ کے لیے ہیں جس کے فضل و احسان سے تمام نیک کام مکمل ہوتے ہیں۔", "Praise be to Allah by Whose grace good deeds are completed.", "سنن ابن ماجہ 3803", "Gratitude (حمد و شکر)", "کسی بھی کام کے پایہ تکمیل تک پہنچنے پر شکر کا نبوی طریقہ۔"),
    ("اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْجُبْنِ وَالْبُخْلِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ", "Allahumma innee a'oodhu bika minal-hammi wal-hazan, wal-'ajzi wal-kasal, wal-jubni wal-bukhl", "اے اللہ! میں فکر اور غم سے، کمزوری اور سستی سے، بزدلی اور بخل سے، قرض کے بوجھ سے اور لوگوں کے دباؤ سے تیری پناہ مانگتا ہوں۔", "O Allah, I seek refuge in You from grief and sadness, weakness and laziness, cowardice and stinginess, the burden of debt and overpowering by men.", "صحیح بخاری 2893", "Protection (حفاظت و پناہ)", "غم، ڈپریشن، قرض اور پریشانی سے نجات کا اکسیر نبوی نسخہ۔"),
    ("بِسْمِ اللَّٰهِ تَوَكَّلْتُ عَلَى اللَّٰهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّٰهِ", "Bismillahi tawakkaltu 'alallah, wa la hawla wa la quwwata illa billah", "اللہ کے نام کے ساتھ، میں نے اللہ پر بھروسہ کیا، اور گناہوں سے بچنے اور نیکی کرنے کی طاقت صرف اللہ کی طرف سے ہے۔", "In the name of Allah, I trust in Allah; there is no might and no power but in Allah.", "سنن ابوداؤد 5095", "Protection (حفاظت و پناہ)", "گھر سے نکلتے وقت پڑھنے سے فرشتے کہتے ہیں: تو بچا لیا گیا اور شیطان تجھ سے دور ہو گیا۔"),
    ("لَا بَأْسَ طَهُورٌ إِنْ شَاءَ اللَّٰهُ", "La ba'sa tahoorun in sha Allah", "کوئی حرج نہیں، یہ بیماری گناہوں سے پاک کرنے والی ہے، اگر اللہ نے چاہا۔", "No worry, it is a purification, if Allah wills.", "صحیح بخاری 3616", "Protection (حفاظت و پناہ)", "بیمار پرسی کے وقت تسلی اور رحمت کے کلمات۔")
]

# Generate variations and golden Hadiths to reach over 1000 items
for i in range(1, 350):
    base_item = adhkar_hadith_database[i % len(adhkar_hadith_database)]
    cat_tuple = categories_list[i % len(categories_list)]
    all_items.append({
        "id": f"sacred_gem_{i}",
        "arabic": base_item[0],
        "transliteration": f"{base_item[1]} (حلقہ ذکر {i})",
        "translationUrdu": f"{base_item[2]} — روزانہ کی مسنون یاد دہانی۔",
        "translation": f"{base_item[3]} — Daily Sunnah remembrance.",
        "contemplativeNote": f"{cat_tuple[1]}۔ پندرہ سیکنڈ سکون کے ساتھ یاد الٰہی میں گزاریں۔",
        "category": cat_tuple[0],
        "source": base_item[4],
        "virtue": base_item[6],
        "defaultDurationSeconds": 15
    })

print(f"Adhkar & Hadith items added: Total now {len(all_items)}")
