import json

items = []

# Helper to add item
def add_item(id_val, arabic, translit, urdu, eng, note, cat, src, virtue):
    items.append({
        "id": id_val,
        "arabic": arabic,
        "transliteration": translit,
        "translationUrdu": urdu,
        "translation": eng,
        "contemplativeNote": note,
        "category": cat,
        "source": src,
        "virtue": virtue,
        "defaultDurationSeconds": 15
    })

# 1. 99 Names of Allah (اسماء الحسنیٰ)
asma_ul_husna = [
    ("الرَّحْمَٰنُ", "Ar-Rahman", "نہایت مہربان، بے پایاں رحم کرنے والا", "The Most Gracious"),
    ("الرَّحِيمُ", "Ar-Raheem", "نہایت رحم فرمانے والا، بار بار رحمت کرنے والا", "The Most Merciful"),
    ("الْمَلِكُ", "Al-Malik", "حقیقی بادشاہ، تمام کائنات کا مالک", "The Sovereign King"),
    ("الْقُدُّوسُ", "Al-Quddus", "نہایت پاکیزہ، ہر عیب سے منزہ", "The Most Pure"),
    ("السَّلَامُ", "As-Salam", "سلامتی دینے والا، ہر آفت سے سلامت", "The Giver of Peace"),
    ("الْمُؤْمِنُ", "Al-Mu'min", "امن و امان دینے والا، تصدیق فرمانے والا", "The Giver of Security"),
    ("الْمُهَيْمِنُ", "Al-Muhaymin", "نگہبان، حفاظت فرمانے والا", "The Overseer"),
    ("الْعَزِيزُ", "Al-Aziz", "سب پر غالب، زبردست قوت والا", "The All-Mighty"),
    ("الْجَبَّارُ", "Al-Jabbar", "ٹوٹی ہوئی حالت سنوارنے والا، زبردست", "The Restorer"),
    ("الْمُتَكَبِّرُ", "Al-Mutakabbir", "بزرگی و بڑائی والا", "The Supreme"),
    ("الْخَالِقُ", "Al-Khaliq", "پیدا فرمانے والا، عدم سے وجود بخشنے والا", "The Creator"),
    ("الْبَارِئُ", "Al-Bari", "ٹھیک ٹھیک بنانے والا", "The Maker"),
    ("الْمُصَوِّرُ", "Al-Musawwir", "صورت گری فرمانے والا", "The Fashioner"),
    ("الْغَفَّارُ", "Al-Ghaffar", "بہت زیادہ بخشنے والا", "The Ever-Forgiving"),
    ("الْقَهَّارُ", "Al-Qahhar", "سب پر مکمل قابو پانے والا", "The All-Subduer"),
    ("الْوَهَّابُ", "Al-Wahhab", "بغیر مانگے کثرت سے عطا فرمانے والا", "The Supreme Bestower"),
    ("الرَّزَّاقُ", "Ar-Razzaq", "سب کو روزی پہنچانے والا", "The Total Provider"),
    ("الْفَتَّاحُ", "Al-Fattah", "رحمت و نصرت کے دروازے کھولنے والا", "The Opener"),
    ("الْعَلِيمُ", "Al-Aleem", "ہر چیز کو مکمل جاننے والا", "The All-Knowing"),
    ("الْقَابِضُ", "Al-Qabid", "روزی اور ارواح کو روکنے والا", "The Withholder"),
    ("الْبَاسِطُ", "Al-Basit", "روزی اور رحمت کشادہ فرمانے والا", "The Extender"),
    ("الْخَافِضُ", "Al-Khafid", "سرکشوں کو پست کرنے والا", "The Abaser"),
    ("الرَّافِعُ", "Ar-Rafi", "اہل ایمان کو بلندی عطا فرمانے والا", "The Exalter"),
    ("الْمُعِزُّ", "Al-Mu'izz", "عزت بخشنے والا", "The Giver of Honor"),
    ("الْمُذِلُّ", "Al-Muzill", "ذلیل و خوار کرنے والا", "The Humiliator"),
    ("السَّمِيعُ", "As-Samee", "سب کچھ سننے والا", "The All-Hearing"),
    ("الْبَصِيرُ", "Al-Baseer", "سب کچھ دیکھنے والا", "The All-Seeing"),
    ("الْحَكَمُ", "Al-Hakam", "حقیقی فیصلہ فرمانے والا", "The Impartial Judge"),
    ("الْعَدْلُ", "Al-Adl", "سراپا عدل و انصاف", "The Utterly Just"),
    ("اللَّطِيفُ", "Al-Lateef", "باریک بین، نہایت نرمی اور مہربانی فرمانے والا", "The Subtle"),
    ("الْخَبِيرُ", "Al-Khabeer", "ہر بات سے باخبر", "The All-Aware"),
    ("الْحَلِيمُ", "Al-Haleem", "نہایت بردبار، جلد سزا نہ دینے والا", "The Most Forbearing"),
    ("الْعَظِيمُ", "Al-Azeem", "بے حد عظمت والا", "The Magnificent"),
    ("الْغَفُورُ", "Al-Ghafoor", "گناہوں کو چھپانے اور معاف فرمانے والا", "The Most Forgiving"),
    ("الشَّكُورُ", "Ash-Shakoor", "تھوڑی نیکی پر بڑا اجر دینے والا", "The Most Appreciative"),
    ("الْعَلِيُّ", "Al-Aliyy", "سب سے بلند و بالا", "The Most High"),
    ("الْكَبِيرُ", "Al-Kabeer", "سب سے بڑا، کبریائی والا", "The Most Great"),
    ("الْحَفِيظُ", "Al-Hafeez", "سب کا نگہبان اور محافظ", "The Preserver"),
    ("الْمُقِيتُ", "Al-Muqeet", "سب کو خوراک و توانائی دینے والا", "The Sustainer"),
    ("الْحَسِيبُ", "Al-Haseeb", "کفایت کرنے والا، حساب لینے والا", "The Reckoner"),
    ("الْجَلِيلُ", "Al-Jaleel", "جلال اور بزرگی والا", "The Majestic"),
    ("الْكَرِيمُ", "Al-Kareem", "نہایت کرم فرمانے والا", "The Most Generous"),
    ("الرَّقِيبُ", "Ar-Raqeeb", "نگران و باخبر", "The Watchful"),
    ("الْمُجِيبُ", "Al-Mujeeb", "دعائیں قبول فرمانے والا", "The Responsive"),
    ("الْوَاسِعُ", "Al-Wasi", "وسیع رحمت و علم والا", "The All-Encompassing"),
    ("الْحَكِيمُ", "Al-Hakeem", "حکمت والا، دانائی کا سرچشمہ", "The All-Wise"),
    ("الْوَدُودُ", "Al-Wadood", "اپنے بندوں سے محبت فرمانے والا", "The Most Loving"),
    ("الْمَجِيدُ", "Al-Majeed", "بزرگی اور فضیلت والا", "The Most Glorious"),
    ("الْبَاعِثُ", "Al-Ba'ith", "مردوں کو زندہ کرنے والا", "The Resurrector"),
    ("الشَّهِيدُ", "Ash-Shaheed", "ہر جگہ حاضر و ناظر", "The All-Observing Witness"),
    ("الْحَقُّ", "Al-Haqq", "سچا معبود، برحق", "The Absolute Truth"),
    ("الْوَكِيلُ", "Al-Wakeel", "بہترین کارساز اور کفیل", "The Supreme Trustee"),
    ("الْقَوِيُّ", "Al-Qawiyy", "قوت و طاقت والا", "The Most Strong"),
    ("الْمَتِينُ", "Al-Mateen", "انتہائی پختہ قوت والا", "The Firm"),
    ("الْوَلِيُّ", "Al-Waliyy", "مددگار اور حامی", "The Protecting Friend"),
    ("الْحَمِيدُ", "Al-Hameed", "تعریف و ثنا کا مستحق", "The Praiseworthy"),
    ("الْمُحْصِي", "Al-Muhsee", "ہر ذرے کا شمار رکھنے والا", "The Appraiser"),
    ("الْمُبْدِئُ", "Al-Mubdi", "پہلی بار پیدا فرمانے والا", "The Originator"),
    ("الْمُعِيدُ", "Al-Mu'eed", "دوبارہ زندہ کرنے والا", "The Restorer"),
    ("الْمُحْيِي", "Al-Muhyee", "زندگی بخشنے والا", "The Giver of Life"),
    ("الْمُمِيتُ", "Al-Mumeet", "موت دینے والا", "The Creator of Death"),
    ("الْحَيُّ", "Al-Hayy", "ہمیشہ زندہ رہنے والا", "The Ever-Living"),
    ("الْقَيُّومُ", "Al-Qayyum", "سب کو قائم رکھنے والا", "The Self-Subsisting Sustainer"),
    ("الْوَاجِدُ", "Al-Wajid", "جو چاہے پا لینے والا", "The Finder"),
    ("الْمَاجِدُ", "Al-Majid", "بڑی شان اور شرف والا", "The Glorious"),
    ("الْوَاحِدُ", "Al-Wahid", "اکیلا اور یکتا", "The One"),
    ("الْأَحَدُ", "Al-Ahad", "یگانہ، جس کی کوئی نظیر نہیں", "The Unique"),
    ("الصَّمَدُ", "As-Samad", "بے نیاز، جس کا سب محتاج ہیں", "The Eternal Refuge"),
    ("الْقَادِرُ", "Al-Qadir", "ہر چیز پر قدرت رکھنے والا", "The Capable"),
    ("الْمُقْتَدِرُ", "Al-Muqtadir", "پوری قدرت و غلبہ رکھنے والا", "The Omnipotent"),
    ("الْمُقَدِّمُ", "Al-Muqaddim", "آگے بڑھانے والا", "The Expediter"),
    ("الْمُؤَخِّرُ", "Al-Mu'akhkhir", "پیچھے رکھنے والا", "The Delayer"),
    ("الْأَوَّلُ", "Al-Awwal", "سب سے پہلا، جس سے پہلے کچھ نہ تھا", "The First"),
    ("الْآخِرُ", "Al-Akhir", "سب کے بعد باقی رہنے والا", "The Last"),
    ("الظَّاهِرُ", "Az-Zahir", "اپنے دلائل سے عیاں", "The Manifest"),
    ("الْبَاطِنُ", "Al-Batin", "نظروں سے پوشیدہ", "The Hidden"),
    ("الْوَالِي", "Al-Wali", "سب کا حاکم اور متولی", "The Sole Governor"),
    ("الْمُتَعَالِي", "Al-Muta'ali", "بلند ترین، برتر", "The Supreme Exalted"),
    ("الْبَرُّ", "Al-Barr", "احسان فرمانے والا، سخی", "The Source of All Goodness"),
    ("التَّوَّابُ", "At-Tawwab", "توبہ قبول فرمانے والا", "The Ever-Pardoning"),
    ("الْمُنْتَقِمُ", "Al-Muntaqim", "سرکشوں سے بدلہ لینے والا", "The Avenger"),
    ("الْعَفُوُّ", "Al-Afuww", "گناہ مٹا دینے والا", "The Supreme Pardoner"),
    ("الرَّءُوفُ", "Ar-Ra'oof", "شفقت اور عنایت فرمانے والا", "The Most Kind"),
    ("مَالِكُ الْمُلْكِ", "Malik-ul-Mulk", "تمام کائنات کی حکومت کا مالک", "Owner of All Dominion"),
    ("ذُو الْجَلَالِ وَالْإِكْرَامِ", "Dhul-Jalali wal-Ikram", "عظمت اور فضل و انعام کا مالک", "Lord of Majesty and Generosity"),
    ("الْمُقْسِطُ", "Al-Muqsit", "انصاف کرنے والا", "The Equitable"),
    ("الْجَامِعُ", "Al-Jami", "سب کو جمع فرمانے والا", "The Gatherer"),
    ("الْغَنِيُّ", "Al-Ghaniyy", "بے پرواہ، غنی", "The Self-Sufficient"),
    ("الْمُغْنِي", "Al-Mughni", "بے نیاز کر دینے والا", "The Enricher"),
    ("الْمَانِعُ", "Al-Mani", "روکنے والا، بچانے والا", "The Preventer"),
    ("الضَّارُّ", "Ad-Darr", "نقصان کا مالک", "The Distressor"),
    ("النَّافِعُ", "An-Nafi", "نفع پہنچانے والا", "The Benefactor"),
    ("النُّورُ", "An-Noor", "زمین اور آسمان کا نور", "The Light"),
    ("الْهَادِي", "Al-Hadi", "ہدایت عطا فرمانے والا", "The Guide"),
    ("الْبَدِيعُ", "Al-Badi", "بے مثال چیزیں پیدا کرنے والا", "The Incomparable Originator"),
    ("الْبَاقِي", "Al-Baqi", "ہمیشہ قائم رہنے والا", "The Everlasting"),
    ("الْوَارِثُ", "Al-Warith", "سب کے بعد وارث رہنے والا", "The Inheritor of All"),
    ("الرَّشِيدُ", "Ar-Rasheed", "درست رہنمائی فرمانے والا", "The Infallible Guide"),
    ("الصَّبُورُ", "As-Saboor", "بے پناہ صبر و حلم والا", "The Most Patient")
]

for idx, (ar, tr, ur, en) in enumerate(asma_ul_husna, 1):
    add_item(
        f"asma_{idx}",
        ar,
        f"Ya {tr}",
        f"{ar}: {ur}",
        f"{ar}: {en}",
        "اس مبارک نام کے معنی میں غور کر کے اللہ تعالیٰ سے دعا مانگیں۔",
        "Asma ul Husna",
        "سنن ترمذی 3507",
        "اللہ کے 99 نام جو یاد کرے گا اور ان کے تقاضوں پر عمل کرے گا وہ جنت میں داخل ہو گا۔"
    )

print(f"Generated Asma ul Husna: {len(items)}")
